# isinstance
print(type(list))
print(type(str))
print(type(int))
print(type(bool))
print(isinstance(type, object))
print(isinstance('type', object))
print(isinstance(123, object))
print(isinstance(2.4, object))
print(isinstance(True, object))
